version: '3'
services:
  database:
    build: ./BaseDeDatos
    container_name: database_mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=q30Gw1nnq560qOlVrWnJ
    - MYSQL_DATABASE=central_database
    ports:
    - "3306:3306"
  fastapi_backend:
    build: ./FrontEndAPI
    container_name: fastapi_backend
    restart: always
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=data_admin
      - DATABASE_PASSWORD=q30Gw1nnq560qOlVrWnJ
      - DATABASE_NAME=central_database
    ports:
    - "8000:8000"