version: '3'
services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    ports:
    - "8001:8000"