version: '3.8'
services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logic_system_api
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    ports:
    - "8002:8000"